package com.merxury.blocker.rule.entity

data class BlockerRule(
    var packageName: String? = "",
    var versionName: String? = "",
    var versionCode: Long? = -1,
    var author: String? = "Blocker",
    var description: String? = "Generated by Blocker",
    var components: MutableList<ComponentRule> = ArrayList()
)