name: Android CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          filename: 'key-blocker.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Decode Google Service key
        id: decode_google_service_key
        uses: timheuer/base64-to-file@v1.1
        with:
          filename: 'google-services.json'
          fileDir: ${{ env.RUNNER_WORKSPACE }}/app/
          encodedString: ${{ secrets.KEY_GOOGLE_SERVICES }}
      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifacts
          path: app/build/outputs/
